include: package:flutter_lints/flutter.yaml
linter:

rules:
     avoid_print: false
     prefer_single_quotes: true
     include: package:solid_lints/analysis_options.yaml
              package:solid_lints/analysis_options_test.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
